# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jpro2023w-container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://jpro2023w.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9b64fba5b8794d84be8a7914c75cef3b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cc3d1df3fbcf43978c28b7176661da41 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: jpro2023w.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9b64fba5b8794d84be8a7914c75cef3b }}/java-container-app:${{ github.sha }}
        file: ./Dockerfile-java-app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jpro2023w-container'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e61e7c18c73945fa8ab50c54dba94f27 }}
        images: 'jpro2023w.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9b64fba5b8794d84be8a7914c75cef3b }}/java-container-app:${{ github.sha }}'
